name: .NET Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Build application
        run: dotnet build --configuration Release
      
      - name: Run tests
        run: dotnet test
 # Step 6: Deploy to Azure App Service
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'YourAppName' # Replace with your Azure App Service name
          slot-name: 'production' # Keep as 'production' unless you're using deployment slots
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ${{ github.workspace }}/YourAppFolder/bin/Release/net6.0/publish # Replace with your build output directory